
import sqlalchemy as sa

from constants import OfferExpireBy, OfferStatus, ReWorkType, OfferRefuseReason, OfferCancelReason, OfferNotifyWay
from constants.commons import null_uuid
from models import meta
from utils.strutils import gen_uuid


tb_offer_record = sa.Table(
    "t_offer_record", meta,
    sa.Column('c_id', sa.String(32), primary_key=True, default=gen_uuid, comment="id", key="id"),
    sa.Column('c_company_id', sa.String(32), comment="企业id", default=null_uuid, key='company_id'),
    sa.Column('c_candidate_id', sa.String(32), comment="候选人id", nullable=False, key="candidate_id"),
    sa.Column('c_candidate_record_id', sa.String(32), comment="应聘记录", nullable=False, key="candidate_record_id"),
    sa.Column('c_is_latest', sa.Boolean, comment="是否是最新offer", default=False, key="is_latest"),
    sa.Column('c_life_dt', sa.Integer, comment="offer有效天数", key="life_dt"),
    sa.Column('c_expire_by', sa.SmallInteger, comment="失效操作人", default=OfferExpireBy.normal, key="expire_by"),
    sa.Column('c_expire_reason_text', sa.String(50), comment="失效原因", default='', key="expire_reason_text"),
    sa.Column('c_expire_dt', sa.DateTime, comment="失效时间", nullable=True, key="expire_dt"),
    sa.Column('c_offer_status', sa.SmallInteger, comment="offer状态", default=OfferStatus.draft, key="offer_status"),
    sa.Column('c_candidate_name', sa.String(35), comment="姓名", nullable=False, key="candidate_name"),
    sa.Column('c_candidate_mobile', sa.String(20), comment="手机号码", nullable=True, default=None, key="candidate_mobile"),
    sa.Column('c_candidate_email', sa.String(100), comment="邮箱", nullable=True, default=None, key="candidate_email"),
    sa.Column('c_candidate_sex', sa.Integer, comment="性别", default=0, key="candidate_sex"),
    sa.Column('c_job_position_id', sa.String(32), comment="应聘职位id", default=None, key="job_position_id"),
    sa.Column('c_job_position_name', sa.String(50), comment="应聘职位名称", default="", key="job_position_name"),
    sa.Column('c_recruitment_channel_name', sa.String(35), comment="招聘渠道", default="", key="recruitment_channel_name"),
    sa.Column('c_dep_id', sa.String(32), comment="部门id", default=None, key="_dep_id"),
    sa.Column('c_dep_name', sa.String(100), comment="部门名称", default="", key="dep_name"),
    sa.Column('c_job_title_id', sa.String(32), comment="岗位id", default=None, key="_job_title_id"),
    sa.Column('c_job_title_name', sa.String(100), comment="岗位名称", nullable=True, default="", key="job_title_name"),
    sa.Column('c_work_type', sa.SmallInteger, comment="工作性质", default=ReWorkType.FULLTIME, key="work_type"),
    sa.Column('c_hire_dt', sa.DateTime, comment="入职日期", nullable=True, default=None, key="hire_dt"),
    sa.Column('c_offer_template', sa.String(32), comment="offer模板", default=None, key="offer_template_id"),
    sa.Column('c_is_send_entry', sa.Boolean, comment="是否发送发送入职登记表", default=False, key="is_send_entry"),
    sa.Column('c_entry_sign', sa.String(32), comment="入职登记表", nullable=True, default=None, key="_entry_sign"),
    sa.Column('c_entry_sign_form_id', sa.String(32), comment="入职登记表模板id", nullable=True, default=True, key="_entry_sign_form_id"),
    sa.Column('c_is_read', sa.Boolean, comment="offer是否阅读", default=False, key="is_read"),
    sa.Column('c_read_dt', sa.DateTime, comment="阅读时间", nullable=True, default=None, key="read_dt"),
    sa.Column('c_is_new_form', sa.Boolean, comment="是否是新入职登记表", default=False, key="is_new_form"),
    sa.Column('c_refuse_reason', sa.SmallInteger, comment="拒绝原因", default=OfferRefuseReason.unmatched_salary, key="refuse_reason"),
    sa.Column('c_refuse_reason_text', sa.String(500), comment="拒绝原因文本", key="refuse_reason_text"),
    sa.Column('c_cancel_reason', sa.SmallInteger, comment="取消录用原因", default=OfferCancelReason.nothing, key="cancel_reason"),
    sa.Column('c_cancel_by_id', sa.String(32), comment="取消人id", default=None, key="cancel_by_id"),
    sa.Column('c_cancel_dt', sa.DateTime, comment="取消录用时间", nullable=True, default=None, key="cancel_dt"),
    sa.Column('c_choose_dt', sa.DateTime, comment="候选人选择时间", nullable=True, default=None, key="choose_dt"),
    sa.Column('c_notify_way', sa.SmallInteger, comment="通知方式", default=OfferNotifyWay.normal, key="notify_way"),
    sa.Column('c_notify_candidate_email', sa.Boolean, comment="是否邮件通知候选人", default=False, key="notify_candidate_email"),
    sa.Column('c_notify_candidate_sms', sa.Boolean, comment="是否短信通知候选人", default=False, key="notify_candidate_sms"),
    sa.Column('c_offer_title', sa.String(100), comment="通知标题", nullable=False, key="offer_title"),
    sa.Column('c_offer_content', sa.Text, comment="通知内容", nullable=False, key="offer_content"),
    sa.Column('c_offer_attach', sa.Text, comment="offer附件", default="", key="offer_attach"),
    sa.Column('c_notify_colleague', sa.Text, comment="通知同事", nullable=True, default=None, key="notify_colleague"),
    sa.Column('c_notify_participants', sa.Boolean, comment="是否通知面试官", default=False, key="notify_participants"),
    sa.Column('c_remark', sa.String(200), comment="备注", default="", key="remark"),
    sa.Column('c_is_real_offer', sa.Boolean, comment="是否真实offer", default=True, key="is_real_offer"),
    sa.Column('c_cc_list', sa.String(2000), comment="抄送列表", nullable=True, default=None, key="cc_list"),
    sa.Column('c_email_address_id', sa.String(32), comment="offer发送邮件配置id", nullable=True, default=True, key="email_address_id"),
    sa.Column('c_add_by_id', sa.String(32), comment="添加人", default=null_uuid, key="add_by_id"),
    sa.Column('c_add_dt', sa.DateTime, comment="添加时间", default=sa.func.now(), key="add_dt"),
    sa.Column('c_update_by_id', sa.String(32), comment="更新人", default=null_uuid, key="update_by_id"),
    sa.Column('c_update_dt', sa.DateTime, comment="更新时间", onupdate=sa.func.now(), key="update_dt"),

    # 已存在的索引
    sa.Index('ix_com_status', 'company_id', 'offer_status', '_dep_id', 'job_position_name'),
    sa.Index('ix_com_job_position', 'job_position_id', 'company_id'),
    sa.Index('ix_com_dep', 'company_id', '_dep_id'),
    sa.Index('ix_candidate', 'candidate_id', 'company_id'),
    sa.Index('ix_name', 'candidate_name'),
    sa.Index('ix_mobile', 'candidate_mobile'),
    sa.Index('ix_email', 'candidate_email'),
    sa.Index('idx_record', 'candidate_record_id'),
)

tb_offer_submit_record = sa.Table(
    "t_offer_submit_record", meta,
    sa.Column('c_id', sa.String(32), primary_key=True, default=gen_uuid, comment="id", key="id"),
    sa.Column('c_company_id', sa.String(32), comment="企业id", default=null_uuid, key='company_id'),
    sa.Column('c_candidate_record_id', sa.String(32), comment="应聘记录", nullable=False, key="candidate_record_id"),
    sa.Column('c_submit_no', sa.String(20), comment="审批编号", key="submit_no"),
    sa.Column('c_submit_id', sa.String(32), comment="审批id", key="submit_id"),
    sa.Column('c_status', sa.Integer, comment="审批状态", key="status"),
    sa.Column('c_emp_id', sa.String(32), comment="发起人id", key="emp_id"),
    sa.Column('c_emp_name', sa.String(20), comment="发起人姓名", key="emp_name"),
    sa.Column('c_approver_id', sa.String(32), comment="审批人ID", key="approver_id"),
    sa.Column('c_approver_name', sa.String(20), comment="审批人姓名", key="approver_name"),
    sa.Column('c_add_dt', sa.DateTime, comment="添加时间", default=sa.func.now(), key="add_dt"),
    sa.Column('c_update_dt', sa.DateTime, comment="修改时间", onupdate=sa.func.now(), key="update_dt"),
    sa.Column('c_is_latest', sa.Boolean, comment="是否最后一条", onupdate=sa.func.now(), key="is_latest"),
)
