"""init mysql

Revision ID: a8e617330f92
Revises: 
Create Date: 2024-06-28 21:49:51.622588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8e617330f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DemoUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('emp')
    op.drop_table('t2')
    op.drop_table('hero')
    op.drop_table('student')
    op.drop_table('dep')
    op.drop_table('score')
    op.drop_table('t1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t1',
    sa.Column('m1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('n1', mysql.CHAR(length=1), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('score',
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False, comment='学号'),
    sa.Column('subject', mysql.VARCHAR(length=30), nullable=True, comment='科目'),
    sa.Column('score', mysql.TINYINT(), autoincrement=False, nullable=False, comment='成绩'),
    sa.PrimaryKeyConstraint('number', 'score'),
    comment='学生成绩表',
    mysql_comment='学生成绩表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('dep',
    sa.Column('name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('add_dt', sa.DATE(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('number', mysql.INTEGER(), autoincrement=True, nullable=False, comment='学号'),
    sa.Column('name', mysql.VARCHAR(length=5), nullable=True, comment='姓名'),
    sa.Column('major', mysql.VARCHAR(length=30), nullable=True, comment='专业'),
    sa.PrimaryKeyConstraint('number'),
    comment='学生信息表',
    mysql_comment='学生信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('hero',
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('number'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('t2',
    sa.Column('m2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('n2', mysql.CHAR(length=1), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('emp',
    sa.Column('ename', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hiredate', sa.DATE(), nullable=True),
    sa.Column('deptno', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sal', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('DemoUser')
    # ### end Alembic commands ###
